feat: GridRow add optional onTap
ted-marozzi/data-grid pull request #3
Opened 2022-11-01 12:38 UTC by defuncart

Adds optional `onTap` to `GridRow`.

2022-11-01 22:05 UTC, ted-marozzi commented on lib/src/components.dart
> +              onLongPress: rows[rowIndex].onLongPress?.call,
Nice, I never knew about this trick

2022-11-01 22:11 UTC, ted-marozzi requested changes

2022-11-01 22:11 UTC, ted-marozzi commented on lib/data_grid.dart
> +export 'package:data_grid/src/components.dart';
I don't think this line is needed.

2022-11-02 06:09 UTC, defuncart commented
@ted-marozzi Ready for re-review :)

2022-11-02 06:19 UTC, ted-marozzi approved these changes

2022-11-02 06:19 UTC, merged